name: Deploy Portfolio front

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.15"

      - name: Install dependencies
        run: yarn install

      - name: Build React app
        run: yarn build

      - name: Deploy to VPS via SSH
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: build/*
          target: /var/www/portfolio-front/
